# Generated by Django 3.1.4 on 2020-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraworkers', '0002_auto_20201218_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_worker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
