# Generated by Django 3.1.4 on 2020-12-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='teachers_profile_picture')),
                ('fname', models.CharField(blank=True, max_length=200, null=True)),
                ('lname', models.CharField(blank=True, max_length=200, null=True)),
                ('fathername', models.CharField(blank=True, max_length=300, null=True)),
                ('mothername', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, choices=[('SE', 'secondary'), ('PR', 'primary'), ('HS', 'higher secondary')], max_length=10, null=True)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('maritual_status', models.CharField(blank=True, choices=[('M', 'married'), ('U', 'unmarried')], max_length=10, null=True)),
            ],
        ),
    ]
