# Generated by Django 3.1.4 on 2020-12-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
