# Generated by Django 3.1.4 on 2020-12-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=200, null=True)),
                ('lname', models.CharField(blank=True, max_length=200, null=True)),
                ('fathername', models.CharField(blank=True, max_length=300, null=True)),
                ('mothername', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_admitted', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=2, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10, null=True)),
            ],
        ),
    ]
