# Generated by Django 3.1.4 on 2020-12-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201218_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='student_profile_picture'),
        ),
    ]
