# Generated by Django 3.1.4 on 2020-12-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201218_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(default='default.png', upload_to='student_profile_picture'),
        ),
    ]
