# Generated by Django 3.1.4 on 2020-12-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201218_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='grade_admitted',
            new_name='class_of',
        ),
    ]
