# Generated by Django 3.1.4 on 2020-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201218_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='admitted_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
