# Generated by Django 3.1.4 on 2020-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_students_admitted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admitted_to',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='students',
            name='class_of',
            field=models.IntegerField(default=2020),
        ),
    ]
